openapi: 3.0.3
info:
  title: NTC Bus Tracking API
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: Login and receive JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password]
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: OK
        '401':
          description: Invalid credentials
  /api/auth/register:
    post:
      summary: Admin creates operator or commuter user
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [username, password, role]
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [operator, commuter]
      responses:
        '201':
          description: Created
        '400':
          description: Invalid role or missing fields
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (admin only)
        '409':
          description: Username already exists
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

